feat: wait for app to start rather than sleep 60

diff --git a/.github/workflows/docker-build-test/action.yml b/.github/workflows/docker-build-test/action.yml
--- a/.github/workflows/docker-build-test/action.yml
+++ b/.github/workflows/docker-build-test/action.yml
@@ -15,5 +15,13 @@ runs:
       shell: bash -l {0}
       run: |
         docker run -p 3001:3001 -d materials-designer:application
-        sleep 60
+        while ! docker logs application 2>&1 | grep "Compiled"; do
+            failed=$(docker logs application 2>&1 | grep "Failed")
+            if [[ "$failed" != "" ]]; then
+                echo "container failed to start"
+                exit 1
+            fi
+            echo "not started yet"
+            sleep 5
+        done
         docker run --network=host materials-designer:test
